import { TrustActions, TrustHero, TrustPage, TrustSectionIntro, trustStyles as styles } from "@/components/trust/trust-page";
import { scaffoldMetadata } from "@/config/metadata";
import { trustFacts } from "@/config/trust";

export const metadata = scaffoldMetadata("Method", "How HKGpipi turns AWS savings opportunities into verified reductions on the bill.");
const decisionGates = ["IDENTIFIED", "Technically valid?", "Economically meaningful?", "Acceptable engineering risk?", "Owner / context known?", "Customer approved?", "Deployed?", "Measured?"];

export default function MethodPage() {
  return <TrustPage>
    <TrustHero eyebrow="METHOD" title="From opportunity to verified saving." summary="HKGpipi owns the path from identifying economically meaningful AWS waste to measuring the result of an approved production change."><p className="technical-label">Operating principle</p><p className={styles.principle}><span>Recommendations are inputs.</span><span>Verified reductions are outcomes.</span></p></TrustHero>
    <section className={styles.section} aria-labelledby="method-detail"><div className="container"><TrustSectionIntro label="01 · Operating method" title="Six stages. One accountable path." titleId="method-detail"><p>Each stage has a purpose, an evidence requirement and a clear output. Production authority remains with the customer.</p></TrustSectionIntro><ol className={styles.stageList} data-testid="method-stages">{trustFacts.operatingStages.map((stage, index) => <li className={styles.stageItem} key={stage.name}><div className={styles.stageIdentity}><span className={styles.stageNumber}>{String(index + 1).padStart(2, "0")}</span><h3>{stage.name}</h3></div><div className={styles.stageField}><span className={styles.fieldLabel}>Purpose</span><p>{stage.purpose}</p></div><div className={styles.stageField}><span className={styles.fieldLabel}>Evidence / action</span><p>{stage.evidence}</p></div><div className={`${styles.stageField} ${styles.stageOutput}`}><span className={styles.fieldLabel}>Output</span><p>{stage.output}</p></div></li>)}</ol></div></section>
    <section className={styles.sectionSurface} aria-labelledby="method-gates"><div className="container"><TrustSectionIntro label="02 · Decision gates" title="An opportunity earns its way forward." titleId="method-gates"><p>A recommendation advances only when the evidence supports the next decision.</p></TrustSectionIntro><ol className={styles.gateSequence} data-testid="method-decision-gates">{decisionGates.map((gate) => <li key={gate}>{gate}</li>)}</ol></div></section>
    <section className={styles.section} aria-labelledby="method-responsibility"><div className="container"><TrustSectionIntro label="03 · Responsibility split" title="Engineering delivery without taking away customer control." titleId="method-responsibility" /><div className={styles.tableFrame} data-testid="method-responsibility"><div className={styles.tableCaption}><strong>Primary roles</strong><span>Not a contractual RACI</span></div><table className={styles.dataTable}><caption className={styles.semanticCaption}>Primary roles from opportunity identification through verification</caption><thead><tr><th scope="col">Decision</th><th scope="col">HKGpipi primary role</th><th scope="col">Customer primary role</th></tr></thead><tbody>{[["Opportunity identification", "Drives analysis", "Provides bounded access and context"], ["Engineering risk validation", "Documents evidence and risk", "Supplies workload and architecture context where required"], ["Change preparation", "Prepares remediation work", "Reviews through existing process"], ["Production approval", "Does not own approval authority", "Retains approval authority"], ["Deployment", "Works with engineering", "Retains deployment control"], ["Verification", "Measures against agreed basis", "Reviews agreed result and basis"]].map(([decision, agency, customer]) => <tr key={decision}><th scope="row">{decision}</th><td data-label="HKGpipi primary role">{agency}</td><td data-label="Customer primary role">{customer}</td></tr>)}</tbody></table></div></div></section>
    <section className={styles.sectionSurface} aria-labelledby="method-traceability"><div className="container"><TrustSectionIntro label="04 · Traceability" title="Keep the saving connected to the change." titleId="method-traceability"><p>Decision evidence stays attached from the identified opportunity through approved remediation and measurement.</p></TrustSectionIntro><p className="technical-label">Illustrative</p><dl className={styles.traceGrid} data-testid="method-traceability">{[["Opportunity", "RDS rightsizing"], ["Expected", "£4,820 / mo"], ["Owner", "Platform"], ["IaC", "infra/prod/rds.tf:118"], ["State", "Approved / illustrative"], ["Change", "db.r6g.4xlarge → db.r6g.2xlarge"], ["Measurement", "Post-change verification pending"]].map(([term, detail]) => <div className={styles.traceItem} key={term}><dt>{term}</dt><dd>{detail}</dd></div>)}</dl><div className={styles.boundaryNote}><strong>Synthetic example</strong><p>This trace is illustrative. It is not customer activity, a live account or a measured customer result.</p></div></div></section>
    <section className={styles.closingSection} aria-labelledby="method-next"><div className="container"><TrustSectionIntro label="05 · Next action" title="Start with bounded discovery." titleId="method-next"><p>The Savings Sprint identifies, validates and ranks the work before implementation begins.</p></TrustSectionIntro><TrustActions secondary={{ href: "/verification", label: "See verification methodology" }} /></div></section>
  </TrustPage>;
}
