import { TrustActions, TrustHero, TrustPage, TrustSectionIntro, trustStyles as styles } from "@/components/trust/trust-page";
import { DirectionalLink } from "@/components/ui/actions";
import { VerificationLine } from "@/components/ui/verification-line";
import { scaffoldMetadata } from "@/config/metadata";
import { trustFacts } from "@/config/trust";

export const metadata = scaffoldMetadata("Verification", "How expected AWS savings become measured, verified annualised savings after change.");

export default function VerificationPage() {
  return <TrustPage>
    <TrustHero eyebrow="VERIFICATION" title="A saving is verified after the change." summary="Expected savings are estimates. HKGpipi measures the post-change billing result and compares it with the agreed baseline before reporting a verified saving."><p className="technical-label">Decision rule</p><p className={styles.principle}><span>Estimate before deployment.</span><span>Measure after deployment.</span></p></TrustHero>
    <section className={styles.section} aria-labelledby="verification-definitions"><div className="container"><TrustSectionIntro label="01 · Definitions" title="Three terms keep the outcome honest." titleId="verification-definitions" /><dl className={styles.definitionGrid} data-testid="verification-definitions"><div className={styles.definition}><dt>Expected saving</dt><dd>An estimate of the economic effect before an approved change is deployed.</dd></div><div className={styles.definition}><dt>30-day measurement view</dt><dd>The observed post-change billing result during the current {trustFacts.measurementView}.</dd></div><div className={styles.definition}><dt>Verified annualised saving</dt><dd>The measured post-change saving, normalised where required and expressed as an annualised value under the agreed verification basis.</dd></div></dl><div className={styles.boundaryNote}><strong>Measurement boundary</strong><p>A 30-day measurement view is a post-change measurement context. It does not mean the whole engagement finishes in 30 days, that every AWS workload requires exactly 30 days, or that the contractual methodology is universally fixed.</p></div></div></section>
    <section className={styles.sectionSurface} aria-labelledby="verification-model"><div className="container"><TrustSectionIntro label="02 · Verification model" title="Reconcile the result against an agreed basis." titleId="verification-model"><p>The baseline and treatment of relevant workload changes are agreed before outcome-based implementation begins.</p></TrustSectionIntro><figure className={styles.equation} data-testid="verification-equation" aria-label="Baseline spend minus normalised post-change spend equals verified saving, which may be expressed as an annualised value."><div className={styles.equationTerms}><div className={styles.equationTerm}><span>Before change</span><strong>Baseline spend</strong></div><span className={styles.equationSymbol} aria-hidden="true">−</span><div className={styles.equationTerm}><span>After change</span><strong>Normalised post-change spend</strong></div><span className={styles.equationSymbol} aria-hidden="true">=</span><div className={`${styles.equationTerm} ${styles.equationResult}`}><span>Measured result</span><strong>Verified saving</strong></div></div><figcaption>Verified saving may be expressed as an annualised value. The agreed basis accounts for relevant changes that would otherwise distort the comparison.</figcaption></figure></div></section>
    <section className={styles.section} aria-labelledby="verification-context"><div className="container"><TrustSectionIntro label="03 · Normalisation" title="Why post-change spend may need context." titleId="verification-context"><p>Factors that may need to be accounted for when interpreting post-change spend include:</p></TrustSectionIntro><ul className={styles.factorList}>{["Workload-volume changes", "Unrelated infrastructure changes", "Pricing changes", "Commitment effects", "Architectural changes outside the approved remediation"].map((factor) => <li key={factor}>{factor}</li>)}</ul></div></section>
    <section className={styles.sectionSurface} aria-labelledby="verification-reconciliation"><div className="container"><TrustSectionIntro label="04 · Measurement" title="Expected becomes verified through reconciliation." titleId="verification-reconciliation" /><div className={styles.measurementGrid}><VerificationLine label="Illustrative reconciliation" context="Expected compared with verified annualised saving" /><ol className={styles.timeline} data-testid="verification-timeline"><li>Deployment</li><li>Day 0</li><li>30-day measurement view</li><li>Verified annualised result</li></ol></div></div></section>
    <section className={styles.section} aria-labelledby="verification-limits"><div className="container"><TrustSectionIntro label="05 · Boundaries" title="What verified does not mean." titleId="verification-limits" /><ul className={styles.boundaryList}><li>The pre-change estimate was exact.</li><li>Every AWS billing movement is attributed to one remediation.</li><li>Workload demand remained unchanged.</li><li>A saving is guaranteed before deployment.</li></ul></div></section>
    <section className={styles.sectionSurface} aria-labelledby="verification-commercial"><div className="container"><TrustSectionIntro label="06 · Commercial boundary" title="Verification is also a commercial boundary." titleId="verification-commercial"><p>For outcome-based implementation, the contractual verification basis is agreed before implementation begins. The 25% fee applies to savings that meet that agreed definition.</p></TrustSectionIntro><div className={styles.inlineAction}><DirectionalLink href="/pricing">Review pricing</DirectionalLink></div><TrustActions secondary={{ href: "/method", label: "Review the operating method" }} /></div></section>
  </TrustPage>;
}
